/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchSymptomsRouteImport } from './routes/search-symptoms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OtpRouteImport } from './routes/otp'
import { Route as Onboarding3RouteImport } from './routes/onboarding-3'
import { Route as Onboarding2RouteImport } from './routes/onboarding-2'
import { Route as Onboarding1RouteImport } from './routes/onboarding-1'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MedicineOverviewRouteImport } from './routes/medicine-overview'
import { Route as MedicalHistoryRouteImport } from './routes/medical-history'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DiseasesRouteImport } from './routes/diseases'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DailySummaryRouteImport } from './routes/daily-summary'
import { Route as DailyPlanRouteImport } from './routes/daily-plan'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AiRecommendationRouteImport } from './routes/ai-recommendation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProgressIndexRouteImport } from './routes/progress.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as DietIndexRouteImport } from './routes/diet.index'
import { Route as ProgressSymptomsRouteImport } from './routes/progress.symptoms'
import { Route as ProgressSleepRouteImport } from './routes/progress.sleep'
import { Route as ProgressPainRouteImport } from './routes/progress.pain'
import { Route as ProgressMoodRouteImport } from './routes/progress.mood'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ProfileReminderRouteImport } from './routes/profile.reminder'
import { Route as ProfilePrivacyRouteImport } from './routes/profile.privacy'
import { Route as ProfileLanguageRouteImport } from './routes/profile.language'
import { Route as ProfileHelpRouteImport } from './routes/profile.help'
import { Route as ProfileHealthRouteImport } from './routes/profile.health'
import { Route as ProfileGoalsRouteImport } from './routes/profile.goals'
import { Route as ProfileAccountRouteImport } from './routes/profile.account'
import { Route as ProfileAboutRouteImport } from './routes/profile.about'
import { Route as MedicineTakenRouteImport } from './routes/medicine.taken'
import { Route as MedicineScheduleRouteImport } from './routes/medicine.schedule'
import { Route as MedicinePrescriptionRouteImport } from './routes/medicine.prescription'
import { Route as MedicineNightRouteImport } from './routes/medicine.night'
import { Route as MedicineMorningRouteImport } from './routes/medicine.morning'
import { Route as MedicineMissedRouteImport } from './routes/medicine.missed'
import { Route as MedicineInsightsRouteImport } from './routes/medicine.insights'
import { Route as MedicineHistoryRouteImport } from './routes/medicine.history'
import { Route as MedicineEmergencyRouteImport } from './routes/medicine.emergency'
import { Route as MedicineAddRouteImport } from './routes/medicine.add'
import { Route as DietWaterRouteImport } from './routes/diet.water'
import { Route as DietTriggerRouteImport } from './routes/diet.trigger'
import { Route as DietNutritionRouteImport } from './routes/diet.nutrition'
import { Route as DietMealPlanRouteImport } from './routes/diet.meal-plan'
import { Route as DietLunchRouteImport } from './routes/diet.lunch'
import { Route as DietLifestyleRouteImport } from './routes/diet.lifestyle'
import { Route as DietDinnerRouteImport } from './routes/diet.dinner'
import { Route as DietBreakfastRouteImport } from './routes/diet.breakfast'
import { Route as DietAvoidRouteImport } from './routes/diet.avoid'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchSymptomsRoute = SearchSymptomsRouteImport.update({
  id: '/search-symptoms',
  path: '/search-symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OtpRoute = OtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const Onboarding3Route = Onboarding3RouteImport.update({
  id: '/onboarding-3',
  path: '/onboarding-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Onboarding2Route = Onboarding2RouteImport.update({
  id: '/onboarding-2',
  path: '/onboarding-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Onboarding1Route = Onboarding1RouteImport.update({
  id: '/onboarding-1',
  path: '/onboarding-1',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineOverviewRoute = MedicineOverviewRouteImport.update({
  id: '/medicine-overview',
  path: '/medicine-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalHistoryRoute = MedicalHistoryRouteImport.update({
  id: '/medical-history',
  path: '/medical-history',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DiseasesRoute = DiseasesRouteImport.update({
  id: '/diseases',
  path: '/diseases',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DailySummaryRoute = DailySummaryRouteImport.update({
  id: '/daily-summary',
  path: '/daily-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyPlanRoute = DailyPlanRouteImport.update({
  id: '/daily-plan',
  path: '/daily-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRecommendationRoute = AiRecommendationRouteImport.update({
  id: '/ai-recommendation',
  path: '/ai-recommendation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressIndexRoute = ProgressIndexRouteImport.update({
  id: '/progress/',
  path: '/progress/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const DietIndexRoute = DietIndexRouteImport.update({
  id: '/diet/',
  path: '/diet/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressSymptomsRoute = ProgressSymptomsRouteImport.update({
  id: '/progress/symptoms',
  path: '/progress/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressSleepRoute = ProgressSleepRouteImport.update({
  id: '/progress/sleep',
  path: '/progress/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressPainRoute = ProgressPainRouteImport.update({
  id: '/progress/pain',
  path: '/progress/pain',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressMoodRoute = ProgressMoodRouteImport.update({
  id: '/progress/mood',
  path: '/progress/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileReminderRoute = ProfileReminderRouteImport.update({
  id: '/profile/reminder',
  path: '/profile/reminder',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePrivacyRoute = ProfilePrivacyRouteImport.update({
  id: '/profile/privacy',
  path: '/profile/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileLanguageRoute = ProfileLanguageRouteImport.update({
  id: '/profile/language',
  path: '/profile/language',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHelpRoute = ProfileHelpRouteImport.update({
  id: '/profile/help',
  path: '/profile/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHealthRoute = ProfileHealthRouteImport.update({
  id: '/profile/health',
  path: '/profile/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileGoalsRoute = ProfileGoalsRouteImport.update({
  id: '/profile/goals',
  path: '/profile/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAccountRoute = ProfileAccountRouteImport.update({
  id: '/profile/account',
  path: '/profile/account',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAboutRoute = ProfileAboutRouteImport.update({
  id: '/profile/about',
  path: '/profile/about',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineTakenRoute = MedicineTakenRouteImport.update({
  id: '/medicine/taken',
  path: '/medicine/taken',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineScheduleRoute = MedicineScheduleRouteImport.update({
  id: '/medicine/schedule',
  path: '/medicine/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicinePrescriptionRoute = MedicinePrescriptionRouteImport.update({
  id: '/medicine/prescription',
  path: '/medicine/prescription',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineNightRoute = MedicineNightRouteImport.update({
  id: '/medicine/night',
  path: '/medicine/night',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineMorningRoute = MedicineMorningRouteImport.update({
  id: '/medicine/morning',
  path: '/medicine/morning',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineMissedRoute = MedicineMissedRouteImport.update({
  id: '/medicine/missed',
  path: '/medicine/missed',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineInsightsRoute = MedicineInsightsRouteImport.update({
  id: '/medicine/insights',
  path: '/medicine/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineHistoryRoute = MedicineHistoryRouteImport.update({
  id: '/medicine/history',
  path: '/medicine/history',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineEmergencyRoute = MedicineEmergencyRouteImport.update({
  id: '/medicine/emergency',
  path: '/medicine/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineAddRoute = MedicineAddRouteImport.update({
  id: '/medicine/add',
  path: '/medicine/add',
  getParentRoute: () => rootRouteImport,
} as any)
const DietWaterRoute = DietWaterRouteImport.update({
  id: '/diet/water',
  path: '/diet/water',
  getParentRoute: () => rootRouteImport,
} as any)
const DietTriggerRoute = DietTriggerRouteImport.update({
  id: '/diet/trigger',
  path: '/diet/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const DietNutritionRoute = DietNutritionRouteImport.update({
  id: '/diet/nutrition',
  path: '/diet/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const DietMealPlanRoute = DietMealPlanRouteImport.update({
  id: '/diet/meal-plan',
  path: '/diet/meal-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const DietLunchRoute = DietLunchRouteImport.update({
  id: '/diet/lunch',
  path: '/diet/lunch',
  getParentRoute: () => rootRouteImport,
} as any)
const DietLifestyleRoute = DietLifestyleRouteImport.update({
  id: '/diet/lifestyle',
  path: '/diet/lifestyle',
  getParentRoute: () => rootRouteImport,
} as any)
const DietDinnerRoute = DietDinnerRouteImport.update({
  id: '/diet/dinner',
  path: '/diet/dinner',
  getParentRoute: () => rootRouteImport,
} as any)
const DietBreakfastRoute = DietBreakfastRouteImport.update({
  id: '/diet/breakfast',
  path: '/diet/breakfast',
  getParentRoute: () => rootRouteImport,
} as any)
const DietAvoidRoute = DietAvoidRouteImport.update({
  id: '/diet/avoid',
  path: '/diet/avoid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-recommendation': typeof AiRecommendationRoute
  '/calendar': typeof CalendarRoute
  '/daily-plan': typeof DailyPlanRoute
  '/daily-summary': typeof DailySummaryRoute
  '/dashboard': typeof DashboardRoute
  '/diseases': typeof DiseasesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/medical-history': typeof MedicalHistoryRoute
  '/medicine-overview': typeof MedicineOverviewRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding-1': typeof Onboarding1Route
  '/onboarding-2': typeof Onboarding2Route
  '/onboarding-3': typeof Onboarding3Route
  '/otp': typeof OtpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search-symptoms': typeof SearchSymptomsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/diet/avoid': typeof DietAvoidRoute
  '/diet/breakfast': typeof DietBreakfastRoute
  '/diet/dinner': typeof DietDinnerRoute
  '/diet/lifestyle': typeof DietLifestyleRoute
  '/diet/lunch': typeof DietLunchRoute
  '/diet/meal-plan': typeof DietMealPlanRoute
  '/diet/nutrition': typeof DietNutritionRoute
  '/diet/trigger': typeof DietTriggerRoute
  '/diet/water': typeof DietWaterRoute
  '/medicine/add': typeof MedicineAddRoute
  '/medicine/emergency': typeof MedicineEmergencyRoute
  '/medicine/history': typeof MedicineHistoryRoute
  '/medicine/insights': typeof MedicineInsightsRoute
  '/medicine/missed': typeof MedicineMissedRoute
  '/medicine/morning': typeof MedicineMorningRoute
  '/medicine/night': typeof MedicineNightRoute
  '/medicine/prescription': typeof MedicinePrescriptionRoute
  '/medicine/schedule': typeof MedicineScheduleRoute
  '/medicine/taken': typeof MedicineTakenRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/account': typeof ProfileAccountRoute
  '/profile/goals': typeof ProfileGoalsRoute
  '/profile/health': typeof ProfileHealthRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/reminder': typeof ProfileReminderRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/progress/mood': typeof ProgressMoodRoute
  '/progress/pain': typeof ProgressPainRoute
  '/progress/sleep': typeof ProgressSleepRoute
  '/progress/symptoms': typeof ProgressSymptomsRoute
  '/diet/': typeof DietIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/progress/': typeof ProgressIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-recommendation': typeof AiRecommendationRoute
  '/calendar': typeof CalendarRoute
  '/daily-plan': typeof DailyPlanRoute
  '/daily-summary': typeof DailySummaryRoute
  '/dashboard': typeof DashboardRoute
  '/diseases': typeof DiseasesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/medical-history': typeof MedicalHistoryRoute
  '/medicine-overview': typeof MedicineOverviewRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding-1': typeof Onboarding1Route
  '/onboarding-2': typeof Onboarding2Route
  '/onboarding-3': typeof Onboarding3Route
  '/otp': typeof OtpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search-symptoms': typeof SearchSymptomsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/diet/avoid': typeof DietAvoidRoute
  '/diet/breakfast': typeof DietBreakfastRoute
  '/diet/dinner': typeof DietDinnerRoute
  '/diet/lifestyle': typeof DietLifestyleRoute
  '/diet/lunch': typeof DietLunchRoute
  '/diet/meal-plan': typeof DietMealPlanRoute
  '/diet/nutrition': typeof DietNutritionRoute
  '/diet/trigger': typeof DietTriggerRoute
  '/diet/water': typeof DietWaterRoute
  '/medicine/add': typeof MedicineAddRoute
  '/medicine/emergency': typeof MedicineEmergencyRoute
  '/medicine/history': typeof MedicineHistoryRoute
  '/medicine/insights': typeof MedicineInsightsRoute
  '/medicine/missed': typeof MedicineMissedRoute
  '/medicine/morning': typeof MedicineMorningRoute
  '/medicine/night': typeof MedicineNightRoute
  '/medicine/prescription': typeof MedicinePrescriptionRoute
  '/medicine/schedule': typeof MedicineScheduleRoute
  '/medicine/taken': typeof MedicineTakenRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/account': typeof ProfileAccountRoute
  '/profile/goals': typeof ProfileGoalsRoute
  '/profile/health': typeof ProfileHealthRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/reminder': typeof ProfileReminderRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/progress/mood': typeof ProgressMoodRoute
  '/progress/pain': typeof ProgressPainRoute
  '/progress/sleep': typeof ProgressSleepRoute
  '/progress/symptoms': typeof ProgressSymptomsRoute
  '/diet': typeof DietIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/progress': typeof ProgressIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-recommendation': typeof AiRecommendationRoute
  '/calendar': typeof CalendarRoute
  '/daily-plan': typeof DailyPlanRoute
  '/daily-summary': typeof DailySummaryRoute
  '/dashboard': typeof DashboardRoute
  '/diseases': typeof DiseasesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/medical-history': typeof MedicalHistoryRoute
  '/medicine-overview': typeof MedicineOverviewRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding-1': typeof Onboarding1Route
  '/onboarding-2': typeof Onboarding2Route
  '/onboarding-3': typeof Onboarding3Route
  '/otp': typeof OtpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search-symptoms': typeof SearchSymptomsRoute
  '/signup': typeof SignupRoute
  '/welcome': typeof WelcomeRoute
  '/diet/avoid': typeof DietAvoidRoute
  '/diet/breakfast': typeof DietBreakfastRoute
  '/diet/dinner': typeof DietDinnerRoute
  '/diet/lifestyle': typeof DietLifestyleRoute
  '/diet/lunch': typeof DietLunchRoute
  '/diet/meal-plan': typeof DietMealPlanRoute
  '/diet/nutrition': typeof DietNutritionRoute
  '/diet/trigger': typeof DietTriggerRoute
  '/diet/water': typeof DietWaterRoute
  '/medicine/add': typeof MedicineAddRoute
  '/medicine/emergency': typeof MedicineEmergencyRoute
  '/medicine/history': typeof MedicineHistoryRoute
  '/medicine/insights': typeof MedicineInsightsRoute
  '/medicine/missed': typeof MedicineMissedRoute
  '/medicine/morning': typeof MedicineMorningRoute
  '/medicine/night': typeof MedicineNightRoute
  '/medicine/prescription': typeof MedicinePrescriptionRoute
  '/medicine/schedule': typeof MedicineScheduleRoute
  '/medicine/taken': typeof MedicineTakenRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/account': typeof ProfileAccountRoute
  '/profile/goals': typeof ProfileGoalsRoute
  '/profile/health': typeof ProfileHealthRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/reminder': typeof ProfileReminderRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/progress/mood': typeof ProgressMoodRoute
  '/progress/pain': typeof ProgressPainRoute
  '/progress/sleep': typeof ProgressSleepRoute
  '/progress/symptoms': typeof ProgressSymptomsRoute
  '/diet/': typeof DietIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/progress/': typeof ProgressIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-recommendation'
    | '/calendar'
    | '/daily-plan'
    | '/daily-summary'
    | '/dashboard'
    | '/diseases'
    | '/forgot-password'
    | '/login'
    | '/medical-history'
    | '/medicine-overview'
    | '/notifications'
    | '/onboarding-1'
    | '/onboarding-2'
    | '/onboarding-3'
    | '/otp'
    | '/reset-password'
    | '/search-symptoms'
    | '/signup'
    | '/welcome'
    | '/diet/avoid'
    | '/diet/breakfast'
    | '/diet/dinner'
    | '/diet/lifestyle'
    | '/diet/lunch'
    | '/diet/meal-plan'
    | '/diet/nutrition'
    | '/diet/trigger'
    | '/diet/water'
    | '/medicine/add'
    | '/medicine/emergency'
    | '/medicine/history'
    | '/medicine/insights'
    | '/medicine/missed'
    | '/medicine/morning'
    | '/medicine/night'
    | '/medicine/prescription'
    | '/medicine/schedule'
    | '/medicine/taken'
    | '/profile/about'
    | '/profile/account'
    | '/profile/goals'
    | '/profile/health'
    | '/profile/help'
    | '/profile/language'
    | '/profile/privacy'
    | '/profile/reminder'
    | '/profile/settings'
    | '/progress/mood'
    | '/progress/pain'
    | '/progress/sleep'
    | '/progress/symptoms'
    | '/diet/'
    | '/profile/'
    | '/progress/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-recommendation'
    | '/calendar'
    | '/daily-plan'
    | '/daily-summary'
    | '/dashboard'
    | '/diseases'
    | '/forgot-password'
    | '/login'
    | '/medical-history'
    | '/medicine-overview'
    | '/notifications'
    | '/onboarding-1'
    | '/onboarding-2'
    | '/onboarding-3'
    | '/otp'
    | '/reset-password'
    | '/search-symptoms'
    | '/signup'
    | '/welcome'
    | '/diet/avoid'
    | '/diet/breakfast'
    | '/diet/dinner'
    | '/diet/lifestyle'
    | '/diet/lunch'
    | '/diet/meal-plan'
    | '/diet/nutrition'
    | '/diet/trigger'
    | '/diet/water'
    | '/medicine/add'
    | '/medicine/emergency'
    | '/medicine/history'
    | '/medicine/insights'
    | '/medicine/missed'
    | '/medicine/morning'
    | '/medicine/night'
    | '/medicine/prescription'
    | '/medicine/schedule'
    | '/medicine/taken'
    | '/profile/about'
    | '/profile/account'
    | '/profile/goals'
    | '/profile/health'
    | '/profile/help'
    | '/profile/language'
    | '/profile/privacy'
    | '/profile/reminder'
    | '/profile/settings'
    | '/progress/mood'
    | '/progress/pain'
    | '/progress/sleep'
    | '/progress/symptoms'
    | '/diet'
    | '/profile'
    | '/progress'
  id:
    | '__root__'
    | '/'
    | '/ai-recommendation'
    | '/calendar'
    | '/daily-plan'
    | '/daily-summary'
    | '/dashboard'
    | '/diseases'
    | '/forgot-password'
    | '/login'
    | '/medical-history'
    | '/medicine-overview'
    | '/notifications'
    | '/onboarding-1'
    | '/onboarding-2'
    | '/onboarding-3'
    | '/otp'
    | '/reset-password'
    | '/search-symptoms'
    | '/signup'
    | '/welcome'
    | '/diet/avoid'
    | '/diet/breakfast'
    | '/diet/dinner'
    | '/diet/lifestyle'
    | '/diet/lunch'
    | '/diet/meal-plan'
    | '/diet/nutrition'
    | '/diet/trigger'
    | '/diet/water'
    | '/medicine/add'
    | '/medicine/emergency'
    | '/medicine/history'
    | '/medicine/insights'
    | '/medicine/missed'
    | '/medicine/morning'
    | '/medicine/night'
    | '/medicine/prescription'
    | '/medicine/schedule'
    | '/medicine/taken'
    | '/profile/about'
    | '/profile/account'
    | '/profile/goals'
    | '/profile/health'
    | '/profile/help'
    | '/profile/language'
    | '/profile/privacy'
    | '/profile/reminder'
    | '/profile/settings'
    | '/progress/mood'
    | '/progress/pain'
    | '/progress/sleep'
    | '/progress/symptoms'
    | '/diet/'
    | '/profile/'
    | '/progress/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiRecommendationRoute: typeof AiRecommendationRoute
  CalendarRoute: typeof CalendarRoute
  DailyPlanRoute: typeof DailyPlanRoute
  DailySummaryRoute: typeof DailySummaryRoute
  DashboardRoute: typeof DashboardRoute
  DiseasesRoute: typeof DiseasesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MedicalHistoryRoute: typeof MedicalHistoryRoute
  MedicineOverviewRoute: typeof MedicineOverviewRoute
  NotificationsRoute: typeof NotificationsRoute
  Onboarding1Route: typeof Onboarding1Route
  Onboarding2Route: typeof Onboarding2Route
  Onboarding3Route: typeof Onboarding3Route
  OtpRoute: typeof OtpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchSymptomsRoute: typeof SearchSymptomsRoute
  SignupRoute: typeof SignupRoute
  WelcomeRoute: typeof WelcomeRoute
  DietAvoidRoute: typeof DietAvoidRoute
  DietBreakfastRoute: typeof DietBreakfastRoute
  DietDinnerRoute: typeof DietDinnerRoute
  DietLifestyleRoute: typeof DietLifestyleRoute
  DietLunchRoute: typeof DietLunchRoute
  DietMealPlanRoute: typeof DietMealPlanRoute
  DietNutritionRoute: typeof DietNutritionRoute
  DietTriggerRoute: typeof DietTriggerRoute
  DietWaterRoute: typeof DietWaterRoute
  MedicineAddRoute: typeof MedicineAddRoute
  MedicineEmergencyRoute: typeof MedicineEmergencyRoute
  MedicineHistoryRoute: typeof MedicineHistoryRoute
  MedicineInsightsRoute: typeof MedicineInsightsRoute
  MedicineMissedRoute: typeof MedicineMissedRoute
  MedicineMorningRoute: typeof MedicineMorningRoute
  MedicineNightRoute: typeof MedicineNightRoute
  MedicinePrescriptionRoute: typeof MedicinePrescriptionRoute
  MedicineScheduleRoute: typeof MedicineScheduleRoute
  MedicineTakenRoute: typeof MedicineTakenRoute
  ProfileAboutRoute: typeof ProfileAboutRoute
  ProfileAccountRoute: typeof ProfileAccountRoute
  ProfileGoalsRoute: typeof ProfileGoalsRoute
  ProfileHealthRoute: typeof ProfileHealthRoute
  ProfileHelpRoute: typeof ProfileHelpRoute
  ProfileLanguageRoute: typeof ProfileLanguageRoute
  ProfilePrivacyRoute: typeof ProfilePrivacyRoute
  ProfileReminderRoute: typeof ProfileReminderRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProgressMoodRoute: typeof ProgressMoodRoute
  ProgressPainRoute: typeof ProgressPainRoute
  ProgressSleepRoute: typeof ProgressSleepRoute
  ProgressSymptomsRoute: typeof ProgressSymptomsRoute
  DietIndexRoute: typeof DietIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ProgressIndexRoute: typeof ProgressIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-symptoms': {
      id: '/search-symptoms'
      path: '/search-symptoms'
      fullPath: '/search-symptoms'
      preLoaderRoute: typeof SearchSymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/otp': {
      id: '/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof OtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-3': {
      id: '/onboarding-3'
      path: '/onboarding-3'
      fullPath: '/onboarding-3'
      preLoaderRoute: typeof Onboarding3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-2': {
      id: '/onboarding-2'
      path: '/onboarding-2'
      fullPath: '/onboarding-2'
      preLoaderRoute: typeof Onboarding2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding-1': {
      id: '/onboarding-1'
      path: '/onboarding-1'
      fullPath: '/onboarding-1'
      preLoaderRoute: typeof Onboarding1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine-overview': {
      id: '/medicine-overview'
      path: '/medicine-overview'
      fullPath: '/medicine-overview'
      preLoaderRoute: typeof MedicineOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-history': {
      id: '/medical-history'
      path: '/medical-history'
      fullPath: '/medical-history'
      preLoaderRoute: typeof MedicalHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diseases': {
      id: '/diseases'
      path: '/diseases'
      fullPath: '/diseases'
      preLoaderRoute: typeof DiseasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-summary': {
      id: '/daily-summary'
      path: '/daily-summary'
      fullPath: '/daily-summary'
      preLoaderRoute: typeof DailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-plan': {
      id: '/daily-plan'
      path: '/daily-plan'
      fullPath: '/daily-plan'
      preLoaderRoute: typeof DailyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-recommendation': {
      id: '/ai-recommendation'
      path: '/ai-recommendation'
      fullPath: '/ai-recommendation'
      preLoaderRoute: typeof AiRecommendationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/': {
      id: '/progress/'
      path: '/progress'
      fullPath: '/progress/'
      preLoaderRoute: typeof ProgressIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet/': {
      id: '/diet/'
      path: '/diet'
      fullPath: '/diet/'
      preLoaderRoute: typeof DietIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/symptoms': {
      id: '/progress/symptoms'
      path: '/progress/symptoms'
      fullPath: '/progress/symptoms'
      preLoaderRoute: typeof ProgressSymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/sleep': {
      id: '/progress/sleep'
      path: '/progress/sleep'
      fullPath: '/progress/sleep'
      preLoaderRoute: typeof ProgressSleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/pain': {
      id: '/progress/pain'
      path: '/progress/pain'
      fullPath: '/progress/pain'
      preLoaderRoute: typeof ProgressPainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress/mood': {
      id: '/progress/mood'
      path: '/progress/mood'
      fullPath: '/progress/mood'
      preLoaderRoute: typeof ProgressMoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/reminder': {
      id: '/profile/reminder'
      path: '/profile/reminder'
      fullPath: '/profile/reminder'
      preLoaderRoute: typeof ProfileReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/privacy': {
      id: '/profile/privacy'
      path: '/profile/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof ProfilePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/language': {
      id: '/profile/language'
      path: '/profile/language'
      fullPath: '/profile/language'
      preLoaderRoute: typeof ProfileLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/help': {
      id: '/profile/help'
      path: '/profile/help'
      fullPath: '/profile/help'
      preLoaderRoute: typeof ProfileHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/health': {
      id: '/profile/health'
      path: '/profile/health'
      fullPath: '/profile/health'
      preLoaderRoute: typeof ProfileHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/goals': {
      id: '/profile/goals'
      path: '/profile/goals'
      fullPath: '/profile/goals'
      preLoaderRoute: typeof ProfileGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/account': {
      id: '/profile/account'
      path: '/profile/account'
      fullPath: '/profile/account'
      preLoaderRoute: typeof ProfileAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/about': {
      id: '/profile/about'
      path: '/profile/about'
      fullPath: '/profile/about'
      preLoaderRoute: typeof ProfileAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine/taken': {
      id: '/medicine/taken'
      path: '/medicine/taken'
      fullPath: '/medicine/taken'
      preLoaderRoute: typeof MedicineTakenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine/schedule': {
      id: '/medicine/schedule'
      path: '/medicine/schedule'
      fullPath: '/medicine/schedule'
      preLoaderRoute: typeof MedicineScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine/prescription': {
      id: '/medicine/prescription'
      path: '/medicine/prescription'
      fullPath: '/medicine/prescription'
      preLoaderRoute: typeof MedicinePrescriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine/night': {
      id: '/medicine/night'
      path: '/medicine/night'
      fullPath: '/medicine/night'
      preLoaderRoute: typeof MedicineNightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine/morning': {
      id: '/medicine/morning'
      path: '/medicine/morning'
      fullPath: '/medicine/morning'
      preLoaderRoute: typeof MedicineMorningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine/missed': {
      id: '/medicine/missed'
      path: '/medicine/missed'
      fullPath: '/medicine/missed'
      preLoaderRoute: typeof MedicineMissedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine/insights': {
      id: '/medicine/insights'
      path: '/medicine/insights'
      fullPath: '/medicine/insights'
      preLoaderRoute: typeof MedicineInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine/history': {
      id: '/medicine/history'
      path: '/medicine/history'
      fullPath: '/medicine/history'
      preLoaderRoute: typeof MedicineHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine/emergency': {
      id: '/medicine/emergency'
      path: '/medicine/emergency'
      fullPath: '/medicine/emergency'
      preLoaderRoute: typeof MedicineEmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine/add': {
      id: '/medicine/add'
      path: '/medicine/add'
      fullPath: '/medicine/add'
      preLoaderRoute: typeof MedicineAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet/water': {
      id: '/diet/water'
      path: '/diet/water'
      fullPath: '/diet/water'
      preLoaderRoute: typeof DietWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet/trigger': {
      id: '/diet/trigger'
      path: '/diet/trigger'
      fullPath: '/diet/trigger'
      preLoaderRoute: typeof DietTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet/nutrition': {
      id: '/diet/nutrition'
      path: '/diet/nutrition'
      fullPath: '/diet/nutrition'
      preLoaderRoute: typeof DietNutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet/meal-plan': {
      id: '/diet/meal-plan'
      path: '/diet/meal-plan'
      fullPath: '/diet/meal-plan'
      preLoaderRoute: typeof DietMealPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet/lunch': {
      id: '/diet/lunch'
      path: '/diet/lunch'
      fullPath: '/diet/lunch'
      preLoaderRoute: typeof DietLunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet/lifestyle': {
      id: '/diet/lifestyle'
      path: '/diet/lifestyle'
      fullPath: '/diet/lifestyle'
      preLoaderRoute: typeof DietLifestyleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet/dinner': {
      id: '/diet/dinner'
      path: '/diet/dinner'
      fullPath: '/diet/dinner'
      preLoaderRoute: typeof DietDinnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet/breakfast': {
      id: '/diet/breakfast'
      path: '/diet/breakfast'
      fullPath: '/diet/breakfast'
      preLoaderRoute: typeof DietBreakfastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diet/avoid': {
      id: '/diet/avoid'
      path: '/diet/avoid'
      fullPath: '/diet/avoid'
      preLoaderRoute: typeof DietAvoidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiRecommendationRoute: AiRecommendationRoute,
  CalendarRoute: CalendarRoute,
  DailyPlanRoute: DailyPlanRoute,
  DailySummaryRoute: DailySummaryRoute,
  DashboardRoute: DashboardRoute,
  DiseasesRoute: DiseasesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MedicalHistoryRoute: MedicalHistoryRoute,
  MedicineOverviewRoute: MedicineOverviewRoute,
  NotificationsRoute: NotificationsRoute,
  Onboarding1Route: Onboarding1Route,
  Onboarding2Route: Onboarding2Route,
  Onboarding3Route: Onboarding3Route,
  OtpRoute: OtpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchSymptomsRoute: SearchSymptomsRoute,
  SignupRoute: SignupRoute,
  WelcomeRoute: WelcomeRoute,
  DietAvoidRoute: DietAvoidRoute,
  DietBreakfastRoute: DietBreakfastRoute,
  DietDinnerRoute: DietDinnerRoute,
  DietLifestyleRoute: DietLifestyleRoute,
  DietLunchRoute: DietLunchRoute,
  DietMealPlanRoute: DietMealPlanRoute,
  DietNutritionRoute: DietNutritionRoute,
  DietTriggerRoute: DietTriggerRoute,
  DietWaterRoute: DietWaterRoute,
  MedicineAddRoute: MedicineAddRoute,
  MedicineEmergencyRoute: MedicineEmergencyRoute,
  MedicineHistoryRoute: MedicineHistoryRoute,
  MedicineInsightsRoute: MedicineInsightsRoute,
  MedicineMissedRoute: MedicineMissedRoute,
  MedicineMorningRoute: MedicineMorningRoute,
  MedicineNightRoute: MedicineNightRoute,
  MedicinePrescriptionRoute: MedicinePrescriptionRoute,
  MedicineScheduleRoute: MedicineScheduleRoute,
  MedicineTakenRoute: MedicineTakenRoute,
  ProfileAboutRoute: ProfileAboutRoute,
  ProfileAccountRoute: ProfileAccountRoute,
  ProfileGoalsRoute: ProfileGoalsRoute,
  ProfileHealthRoute: ProfileHealthRoute,
  ProfileHelpRoute: ProfileHelpRoute,
  ProfileLanguageRoute: ProfileLanguageRoute,
  ProfilePrivacyRoute: ProfilePrivacyRoute,
  ProfileReminderRoute: ProfileReminderRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProgressMoodRoute: ProgressMoodRoute,
  ProgressPainRoute: ProgressPainRoute,
  ProgressSleepRoute: ProgressSleepRoute,
  ProgressSymptomsRoute: ProgressSymptomsRoute,
  DietIndexRoute: DietIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ProgressIndexRoute: ProgressIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
