// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  const mockAuth = {
    signUp: async ({ email, password, options }: any) => {
      const name = options?.data?.name || email.split('@')[0];
      if (typeof window !== 'undefined') {
        localStorage.setItem('demo_name', name);
        localStorage.setItem('demo_email', email);
      }
      return { data: { user: { id: 'demo-user-id', email, user_metadata: { name } } }, error: null };
    },
    signInWithPassword: async ({ email }: any) => {
      if (typeof window !== 'undefined') {
        localStorage.setItem('demo_email', email);
        if (!localStorage.getItem('demo_name')) {
          localStorage.setItem('demo_name', email.split('@')[0]);
        }
      }
      return { data: { user: { id: 'demo-user-id', email, user_metadata: { name: email.split('@')[0] } } }, error: null };
    },
    signOut: async () => {
      if (typeof window !== 'undefined') {
        localStorage.removeItem('demo_email');
        localStorage.removeItem('demo_name');
      }
      return { error: null };
    },
    getUser: async () => {
      const email = typeof window !== 'undefined' ? localStorage.getItem('demo_email') : null;
      const name = typeof window !== 'undefined' ? localStorage.getItem('demo_name') : null;
      if (email) {
        return { data: { user: { id: 'demo-user-id', email, user_metadata: { name } } }, error: null };
      }
      return { data: { user: null }, error: null };
    },
    getSession: async () => {
      const email = typeof window !== 'undefined' ? localStorage.getItem('demo_email') : null;
      if (email) {
        return {
          data: {
            session: {
              access_token: 'demo-session-token',
              user: { id: 'demo-user-id', email }
            }
          },
          error: null
        };
      }
      return { data: { session: null }, error: null };
    },
    resetPasswordForEmail: async (email: string) => {
      if (typeof window !== 'undefined') {
        localStorage.setItem('reset_email', email);
        const mockOtp = Math.floor(1000 + Math.random() * 9000).toString();
        localStorage.setItem('reset_otp', mockOtp);
        console.log(`[Supabase Auth] Password reset OTP for ${email}: ${mockOtp}`);
      }
      return { data: {}, error: null };
    },
    verifyOtp: async ({ email, token }: any) => {
      if (typeof window !== 'undefined') {
        const storedOtp = localStorage.getItem('reset_otp');
        if (token && storedOtp && token.toString().trim() !== storedOtp) {
          return { data: { session: null }, error: { message: "Invalid OTP verification code. Please check your email." } };
        }
      }
      return { data: { session: { access_token: "demo-token" } }, error: null };
    },
    updateUser: async ({ password }: any) => {
      if (typeof window !== 'undefined') {
        localStorage.setItem('demo_password', password);
      }
      return { data: { user: {} }, error: null };
    },
    onAuthStateChange: (callback: any) => {
      return { data: { subscription: { unsubscribe: () => {} } } };
    }
  };

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || SUPABASE_URL.includes('yourproject') || SUPABASE_URL === 'YOUR_SUPABASE_URL') {
    console.warn('[Supabase] Missing or placeholder environment variable(s). falling back to offline/demo mode.');
    return {
      auth: mockAuth,
      from: () => ({
        select: () => Promise.resolve({ data: [], error: null }),
        insert: () => Promise.resolve({ data: null, error: null }),
        update: () => Promise.resolve({ data: null, error: null }),
        delete: () => Promise.resolve({ data: null, error: null }),
        eq: function() { return this; },
        single: () => Promise.resolve({ data: null, error: null }),
      }),
    } as any;
  }

  const realClient = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });

  return {
    ...realClient,
    auth: {
      ...realClient.auth,
      signUp: async (args: any) => {
        try {
          const res = await realClient.auth.signUp(args);
          if (res.error && (res.error.message?.includes('Failed to fetch') || res.error.name === 'AuthRetryableFetchError')) {
            return mockAuth.signUp(args);
          }
          return res;
        } catch (err: any) {
          console.warn('[Supabase] Network error during signUp, using demo fallback:', err);
          return mockAuth.signUp(args);
        }
      },
      signInWithPassword: async (args: any) => {
        try {
          const res = await realClient.auth.signInWithPassword(args);
          if (res.error && (res.error.message?.includes('Failed to fetch') || res.error.name === 'AuthRetryableFetchError')) {
            return mockAuth.signInWithPassword(args);
          }
          return res;
        } catch (err: any) {
          console.warn('[Supabase] Network error during signInWithPassword, using demo fallback:', err);
          return mockAuth.signInWithPassword(args);
        }
      },
      getUser: async () => {
        try {
          const res = await realClient.auth.getUser();
          if (res.error || !res.data.user) return mockAuth.getUser();
          return res;
        } catch {
          return mockAuth.getUser();
        }
      },
      getSession: async () => {
        try {
          const res = await realClient.auth.getSession();
          if (res.error || !res.data.session) return mockAuth.getSession();
          return res;
        } catch {
          return mockAuth.getSession();
        }
      }
    }
  } as any;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

