// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY || SUPABASE_URL.includes('yourproject') || SUPABASE_URL === 'YOUR_SUPABASE_URL') {
    console.warn('[Supabase] Missing or placeholder environment variable(s). falling back to offline/demo mode.');
    return {
      auth: {
        signUp: async ({ email, password, options }: any) => {
          const name = options?.data?.name || email.split('@')[0];
          if (typeof window !== 'undefined') {
            localStorage.setItem('demo_name', name);
            localStorage.setItem('demo_email', email);
          }
          return { data: { user: { id: 'demo-user-id', email, user_metadata: { name } } }, error: null };
        },
        signInWithPassword: async ({ email }: any) => {
          if (typeof window !== 'undefined') {
            localStorage.setItem('demo_email', email);
            if (!localStorage.getItem('demo_name')) {
              localStorage.setItem('demo_name', email.split('@')[0]);
            }
          }
          return { data: { user: { id: 'demo-user-id', email, user_metadata: { name: email.split('@')[0] } } }, error: null };
        },
        signOut: async () => {
          if (typeof window !== 'undefined') {
            localStorage.removeItem('demo_email');
            localStorage.removeItem('demo_name');
          }
          return { error: null };
        },
        getUser: async () => {
          const email = typeof window !== 'undefined' ? localStorage.getItem('demo_email') : null;
          const name = typeof window !== 'undefined' ? localStorage.getItem('demo_name') : null;
          if (email) {
            return { data: { user: { id: 'demo-user-id', email, user_metadata: { name } } }, error: null };
          }
          return { data: { user: null }, error: null };
        },
        getSession: async () => {
          const email = typeof window !== 'undefined' ? localStorage.getItem('demo_email') : null;
          if (email) {
            return {
              data: {
                session: {
                  access_token: 'demo-session-token',
                  user: { id: 'demo-user-id', email }
                }
              },
              error: null
            };
          }
          return { data: { session: null }, error: null };
        },
        onAuthStateChange: (callback: any) => {
          return { data: { subscription: { unsubscribe: () => {} } } };
        }
      },
      from: () => ({
        select: () => Promise.resolve({ data: [], error: null }),
        insert: () => Promise.resolve({ data: null, error: null }),
        update: () => Promise.resolve({ data: null, error: null }),
        delete: () => Promise.resolve({ data: null, error: null }),
        eq: function() { return this; },
        single: () => Promise.resolve({ data: null, error: null }),
      }),
    } as any;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

